import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  sidebarContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
    width: "100%",
  },
  headerRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 16 : 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#eef5ee",
    backgroundColor: "#ffffff",
  },
  closeButton: {
    padding: 4,
  },
  headerTitle: {
    fontFamily: "Manrope",
    fontSize: 20,
    fontWeight: "700",
    color: "#161d19",
  },
  clearAllText: {
    fontFamily: "Manrope",
    fontSize: 14,
    color: "#6c7a71",
    fontWeight: "500",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  sectionContainer: {
    marginTop: 24,
    width: "100%",
  },
  sectionHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionIcon: {
    marginLeft: 8,
  },
  sectionTitle: {
    fontFamily: "Manrope",
    fontSize: 16,
    fontWeight: "700",
    color: "#161d19",
  },
  capsuleContainer: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 8,
  },
  capsule: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#bbcac0",
    backgroundColor: "#ffffff",
  },
  capsuleActive: {
    backgroundColor: "#11b67f",
    borderColor: "#11b67f",
  },
  capsuleText: {
    fontFamily: "Manrope",
    fontSize: 14,
    color: "#3c4a42",
  },
  capsuleTextActive: {
    color: "#ffffff",
    fontWeight: "600",
  },
  searchContainer: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: "#eef5ee",
    borderRadius: 20,
    paddingHorizontal: 14,
    height: 46,
    marginBottom: 12,
    width: "100%",
  },
  searchIcon: {
    marginLeft: 8,
  },
  searchInput: {
    flex: 1,
    fontFamily: "Manrope",
    fontSize: 14,
    color: "#161d19",
    textAlign: "right",
    paddingVertical: 0,
    // إلغاء خط التحديد الأسود تماماً على الويب والمحاكي
    ...Platform.select({
      web: {
        outlineStyle: "none",
        outlineWidth: 0,
      },
    }),
  },
  brandWrapper: {
    borderWidth: 1,
    borderColor: "#eef5ee",
    borderRadius: 16,
    paddingHorizontal: 8,
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  brandList: {
    maxHeight: 200,
  },
  brandRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f7fbf7",
    width: "100%",
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#bbcac0",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
    backgroundColor: "#fff",
  },
  checkboxChecked: {
    backgroundColor: "#11b67f",
    borderColor: "#11b67f",
  },
  brandLabel: {
    fontFamily: "Manrope",
    fontSize: 15,
    color: "#3c4a42",
    flex: 1,
    textAlign: "right",
  },
  brandLabelChecked: {
    color: "#161d19",
    fontWeight: "600",
  },
  sliderMockContainer: {
    height: 40,
    justifyContent: "center",
    marginVertical: 10,
    width: "100%",
  },
  sliderLine: {
    height: 4,
    backgroundColor: "#e8f0e9",
    borderRadius: 2,
    position: "relative",
  },
  sliderActiveLine: {
    position: "absolute",
    left: 0,
    height: 4,
    backgroundColor: "#11b67f",
    borderRadius: 2,
  },
  sliderThumb: {
    position: "absolute",
    top: -8,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#11b67f",
    borderWidth: 2,
    borderColor: "#ffffff",
    marginLeft: -10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  priceInputRow: {
    flexDirection: "row-reverse",
    gap: 16,
    marginTop: 10,
    width: "100%",
  },
  priceInputBox: {
    flex: 1,
  },
  priceLabel: {
    fontFamily: "Manrope",
    fontSize: 13,
    color: "#6c7a71",
    marginBottom: 6,
    marginRight: 4,
    textAlign: "right",
  },
  priceInput: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#bbcac0",
    borderRadius: 14,
    height: 44,
    paddingHorizontal: 12,
    fontFamily: "Manrope",
    fontSize: 15,
    color: "#161d19",
    textAlign: "center",
    // حماية مدخلات الأسعار السفلية من الإطار الأسود أيضاً
    ...Platform.select({
      web: {
        outlineStyle: "none",
        outlineWidth: 0,
      },
    }),
  },
  switchSection: {
    marginTop: 28,
    borderTopWidth: 1,
    borderTopColor: "#eef5ee",
    paddingTop: 20,
    gap: 18,
    width: "100%",
  },
  switchRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
  },
  switchLeft: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 12,
  },
  switchLabel: {
    fontFamily: "Manrope",
    fontSize: 15,
    color: "#161d19",
    fontWeight: "500",
  },
  footerContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#ffffff",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: "#dde4dd",
  },
  applyButton: {
    backgroundColor: "#11b67f",
    borderRadius: 18,
    height: 54,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#11b67f",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  applyButtonText: {
    fontFamily: "Manrope",
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
  },
});
