import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f6f8f7" },
  mainWrapper: {
    maxWidth: 1440,
    alignSelf: "center",
    width: "100%",
    paddingVertical: 24,
    paddingHorizontal: 12,
  },
  toolsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 32,
    gap: 16,
    zIndex: 10, // 👈 قللناها عشان السيرش يغطي عليها
    elevation: 10, // 👈 قللناها
  },
  breadcrumb: { flexDirection: "row", alignItems: "center", gap: 8 },
  crumbText: { fontSize: 14, fontWeight: "600", color: "#64748b" },
  crumbActive: { fontSize: 14, fontWeight: "bold", color: "#0f172a" },
  toolsActions: {
    flex: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "flex-end",
    zIndex: 20, // 👈 عشان سيرش الديسكتوب
    elevation: 20,
  },
  mobileFilterBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  filterBtnText: { fontSize: 14, fontWeight: "bold", color: "#0f172a" },
  contentLayout: {
    flexDirection: "row",
    gap: 40,
  },
  productCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    overflow: "hidden",
    marginBottom: 12,
    ...Platform.select({
      web: { cursor: "pointer", transition: "all 0.3s ease" },
    }),
  },
  imageContainer: {
    width: "100%",
    aspectRatio: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    padding: 2,
  },
  productImage: {
    width: "100%",
    height: "100%",
  },
  stockBadge: {
    position: "absolute",
    top: 6,
    left: 6,
    backgroundColor: "#10b77f",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    zIndex: 10,
  },
  stockBadgeText: {
    color: "#fff",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0,
  },
  discountBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    backgroundColor: "#ef4444",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    zIndex: 10,
  },
  discountBadgeText: {
    color: "#fff",
    fontSize: 9,
    fontWeight: "900",
  },
  infoContainer: {
    padding: 8,
    flex: 1,
    justifyContent: "space-between",
  },
  textStack: { marginBottom: 6 },
  brandName: {
    fontSize: 9,
    fontWeight: "800",
    color: "#94a3b8",
    textTransform: "uppercase",
    marginBottom: 2,
    textAlign: "left",
  },
  enName: {
    fontSize: 11,
    fontWeight: "800",
    color: "#0f172a",
    minHeight: 32,
    lineHeight: 16,
    textAlign: "left",
  },
  priceContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 4,
  },
  priceColumn: {
    flexDirection: "column",
    justifyContent: "flex-end",
  },
  oldPrice: {
    fontSize: 10,
    color: "#94a3b8",
    textDecorationLine: "line-through",
    marginBottom: 1,
  },
  mainPriceRow: { flexDirection: "row", alignItems: "baseline", gap: 2 },
  finalPrice: { fontSize: 13, fontWeight: "900", color: "#10b77f" },
  currency: { fontSize: 9, fontWeight: "bold", color: "#10b77f" },
  floatingAddBtn: {
    width: 26,
    height: 26,
    backgroundColor: "#10b77f",
    borderRadius: 13,
    justifyContent: "center",
    alignItems: "center",
  },
  floatingRemoveBtn: {
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#ef4444",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  modalTitle: { fontSize: 20, fontWeight: "bold", color: "#0f172a" },
  paginationSection: {
    marginTop: 32,
    alignItems: "center",
    paddingBottom: 20,
  },
  paginationRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  pageButton: {
    minWidth: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 12,
  },
  activePageButton: {
    backgroundColor: "#10b77f",
    borderColor: "#10b77f",
  },
  pageButtonText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#64748b",
  },
  activePageButtonText: {
    color: "#fff",
  },
  pageText: {
    fontSize: 13,
    color: "#94a3b8",
    fontWeight: "600",
  },
});
