version: "3.8"

services:
  pharmacy-api:
    build: .
    container_name: pharmacy-api
    network_mode: "host"
    env_file:
      - .env.production
    restart: always
    volumes:
      - ./static:/app/static # عشان لو رفعت صور تفضل موجودة حتى لو الـ container اتمسح
