version: "3.8"

services:
  # 1️⃣ خدمة قاعدة البيانات (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: pg_db
    environment:
      # سحب البيانات مباشرة من ملف الـ env لضمان التطابق
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # الحفاظ على البيانات عند إعادة التشغيل
    restart: always

  # 2️⃣ خدمة الباك إند (FastAPI)
  pharmacy-api:
    build: .
    container_name: pharmacy-app
    ports:
      - "8001:8000" # الباب الخارجي للسيرفر 8001
    env_file:
      - .env.production # إجبار الحاوية على قراءة ملف الإنتاج
    depends_on:
      - db # ضمان تشغيل الداتابيز أولاً
    restart: always
    volumes:
      - ./static:/app/static # لرفع وحفظ الصور
      - ./ecommerce_backend/.env.production:/app/.env.production # ربط ملف الإعدادات داخل الحاوية

# تعريف وحدات التخزين المستقلة
volumes:
  pgdata:
