version: "3.8"

services:
  api:
    build: .
    container_name: pharmacy_backend
    ports:
      - "8004:8000" # بنربط بورت 8004 اللي إنت شغال بيه ببورت 8000 جوه الدوكر
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app # عشان لو عدلت في الكود يسمع فوراً وإنت بتعمل تيست
