import { StyleSheet, Platform, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const COLORS = {
  primary: "#10b748",
  bgLight: "#f6f8f6",
  white: "#ffffff",
  slate900: "#0f172a",
  slate700: "#334155",
  slate600: "#475569",
  slate500: "#64748b",
  slate400: "#94a3b8",
  slate200: "#e2e8f0",
  slate100: "#f1f5f9",
  slate50: "#f8fafc",
  skyAccent: "#38BDF8",
};

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: COLORS.bgLight,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    paddingVertical: Platform.OS === "web" ? 40 : 20,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.7)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
    borderRadius: 24,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.slate200,
    width: "100%",
    maxWidth: 480,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 5,
    overflow: "hidden",
    position: "relative",
  },
  logoSection: {
    paddingTop: 48,
    paddingBottom: 32,
    alignItems: "center",
  },
  logoCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(16, 183, 72, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  appName: {
    fontSize: 26,
    fontWeight: "900",
    color: COLORS.slate900,
    letterSpacing: -0.5,
  },
  welcomeSection: {
    paddingHorizontal: 32,
    paddingBottom: 32,
    alignItems: "center",
  },
  welcomeTitle: {
    fontSize: width < 380 ? 26 : 32,
    fontWeight: "900",
    color: COLORS.slate900,
    marginBottom: 8,
    textAlign: "center",
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: COLORS.slate500,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 24,
  },
  formSection: {
    paddingHorizontal: 32,
    paddingBottom: 32,
  },
  primaryGoogleBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
    height: 60,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.slate200,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    ...Platform.select({
      web: { cursor: "pointer", transition: "all 0.2s ease" },
    }),
  },
  primaryGoogleBtnText: {
    fontSize: 17,
    fontWeight: "700",
    color: COLORS.slate700,
  },
  banner: {
    marginHorizontal: 32,
    marginBottom: 32,
    padding: 16,
    backgroundColor: "rgba(16, 183, 72, 0.05)",
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(16, 183, 72, 0.1)",
  },
  bannerIconBox: {
    width: 40,
    height: 40,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  bannerContent: { flex: 1 },
  bannerTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.primary,
    textTransform: "uppercase",
    marginBottom: 2,
    letterSpacing: 0.5,
  },
  bannerText: {
    fontSize: 13,
    fontWeight: "500",
    color: COLORS.slate600,
    lineHeight: 18,
  },
  cardFooter: {
    backgroundColor: COLORS.slate50,
    paddingVertical: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: COLORS.slate200,
  },
  footerText: {
    color: COLORS.slate500,
    fontWeight: "600",
    fontSize: 14,
  },
  signUpLink: {
    color: COLORS.primary,
    fontWeight: "800",
    fontSize: 14,
    marginLeft: 6,
  },
  copyrightText: {
    textAlign: "center",
    fontSize: 12,
    color: COLORS.slate400,
    marginTop: 24,
    lineHeight: 18,
    paddingHorizontal: 40,
  },
  rtlFab: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    borderWidth: 1,
    borderColor: COLORS.slate200,
  },
});
