"""add discount fields to bundle item

Revision ID: 3872f2691ea3
Revises: 85ff74b0af2d
Create Date: 2026-06-13 18:09:18.861243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3872f2691ea3'
down_revision: Union[str, Sequence[str], None] = '85ff74b0af2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bundle', 'slug',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.create_index(op.f('ix_Bundle_name_en'), 'Bundle', ['name_en'], unique=True)
    op.add_column('BundleItem', sa.Column('bundle_name', sa.String(length=150), nullable=False))
    op.add_column('BundleItem', sa.Column('short_item_no', sa.String(length=40), nullable=False))
    op.add_column('BundleItem', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('BundleItem', sa.Column('discount_value', sa.Numeric(precision=18, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.drop_constraint(op.f('BundleItem_bundle_id_fkey'), 'BundleItem', type_='foreignkey')
    op.drop_constraint(op.f('BundleItem_product_id_fkey'), 'BundleItem', type_='foreignkey')
    op.create_foreign_key(None, 'BundleItem', 'Bundle', ['bundle_name'], ['name_en'], ondelete='CASCADE')
    op.create_foreign_key(None, 'BundleItem', 'Product', ['short_item_no'], ['short_item_no'], ondelete='CASCADE')
    op.drop_column('BundleItem', 'bundle_id')
    op.drop_column('BundleItem', 'product_id')
    op.alter_column('Category', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('Category', 'slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('idx_category_name'), table_name='Category')
    op.drop_index(op.f('idx_category_parent'), table_name='Category')
    op.create_index(op.f('ix_Category_name'), 'Category', ['name'], unique=False)
    op.create_index(op.f('ix_Category_parent_id'), 'Category', ['parent_id'], unique=False)
    op.alter_column('Orders', 'shipping_governorate',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Orders', 'shipping_city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_Product_short_item_no'), table_name='Product')
    op.create_index(op.f('ix_Product_short_item_no'), 'Product', ['short_item_no'], unique=True)
    op.alter_column('Purchase', 'supplier_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Sales', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'ar_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'en_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'Brand_Name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'header',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'sub_header',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('idx_shortitemno_ar_name'), table_name='ShortItemNo')
    op.drop_index(op.f('idx_shortitemno_en_name'), table_name='ShortItemNo')
    op.create_index(op.f('ix_ShortItemNo_ar_name'), 'ShortItemNo', ['ar_name'], unique=False)
    op.create_index(op.f('ix_ShortItemNo_en_name'), 'ShortItemNo', ['en_name'], unique=False)
    op.alter_column('Supplier', 'supplier_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('Supplier', 'contact_person',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Supplier', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('addresses', 'governorate',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('banners', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('product_images', 'alt_text',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('idx_product_images_main'), table_name='product_images')
    op.drop_index(op.f('idx_product_images_sku'), table_name='product_images')
    op.create_index(op.f('ix_product_images_is_main'), 'product_images', ['is_main'], unique=False)
    op.create_index(op.f('ix_product_images_short_item_no'), 'product_images', ['short_item_no'], unique=False)
    op.alter_column('return_sales', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('return_sales', 'customer_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_product_images_short_item_no'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_is_main'), table_name='product_images')
    op.create_index(op.f('idx_product_images_sku'), 'product_images', ['short_item_no'], unique=False)
    op.create_index(op.f('idx_product_images_main'), 'product_images', ['is_main'], unique=False)
    op.alter_column('product_images', 'alt_text',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('banners', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('addresses', 'city',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('addresses', 'governorate',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('Supplier', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('Supplier', 'contact_person',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('Supplier', 'supplier_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_ShortItemNo_en_name'), table_name='ShortItemNo')
    op.drop_index(op.f('ix_ShortItemNo_ar_name'), table_name='ShortItemNo')
    op.create_index(op.f('idx_shortitemno_en_name'), 'ShortItemNo', ['en_name'], unique=False)
    op.create_index(op.f('idx_shortitemno_ar_name'), 'ShortItemNo', ['ar_name'], unique=False)
    op.alter_column('ShortItemNo', 'sub_header',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'header',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'Brand_Name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'en_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'ar_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('Sales', 'customer_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('Purchase', 'supplier_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_Product_short_item_no'), table_name='Product')
    op.create_index(op.f('ix_Product_short_item_no'), 'Product', ['short_item_no'], unique=False)
    op.alter_column('Orders', 'shipping_city',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('Orders', 'shipping_governorate',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_Category_parent_id'), table_name='Category')
    op.drop_index(op.f('ix_Category_name'), table_name='Category')
    op.create_index(op.f('idx_category_parent'), 'Category', ['parent_id'], unique=False)
    op.create_index(op.f('idx_category_name'), 'Category', ['name'], unique=False)
    op.alter_column('Category', 'slug',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('Category', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('BundleItem', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('BundleItem', sa.Column('bundle_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'BundleItem', type_='foreignkey')
    op.drop_constraint(None, 'BundleItem', type_='foreignkey')
    op.create_foreign_key(op.f('BundleItem_product_id_fkey'), 'BundleItem', 'Product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('BundleItem_bundle_id_fkey'), 'BundleItem', 'Bundle', ['bundle_id'], ['id'], ondelete='CASCADE')
    op.drop_column('BundleItem', 'discount_value')
    op.drop_column('BundleItem', 'discount_percentage')
    op.drop_column('BundleItem', 'short_item_no')
    op.drop_column('BundleItem', 'bundle_name')
    op.drop_index(op.f('ix_Bundle_name_en'), table_name='Bundle')
    op.alter_column('Bundle', 'slug',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
