"""Add dosage and usage_instructions to ShortItemNo

Revision ID: 85ff74b0af2d
Revises: c4cbece81283
Create Date: 2026-04-26 21:19:15.044917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ff74b0af2d'
down_revision: Union[str, Sequence[str], None] = 'c4cbece81283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('Category', 'slug',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.create_index(op.f('ix_Category_name'), 'Category', ['name'], unique=False)
    op.create_index(op.f('ix_Category_parent_id'), 'Category', ['parent_id'], unique=False)
    op.alter_column('Orders', 'shipping_governorate',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Orders', 'shipping_city',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Purchase', 'supplier_name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Sales', 'customer_name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.add_column('ShortItemNo', sa.Column('dosage', sa.String(length=255), nullable=True))
    op.add_column('ShortItemNo', sa.Column('usage_instructions', sa.Text(), nullable=True))
    op.alter_column('ShortItemNo', 'ar_name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'en_name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'Brand_Name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'header',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'sub_header',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.create_index(op.f('ix_ShortItemNo_ar_name'), 'ShortItemNo', ['ar_name'], unique=False)
    op.create_index(op.f('ix_ShortItemNo_en_name'), 'ShortItemNo', ['en_name'], unique=False)
    op.alter_column('Supplier', 'supplier_name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('Supplier', 'contact_person',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Supplier', 'email',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('addresses', 'governorate',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('banners', 'title',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('product_images', 'alt_text',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.create_index(op.f('ix_product_images_is_main'), 'product_images', ['is_main'], unique=False)
    op.create_index(op.f('ix_product_images_short_item_no'), 'product_images', ['short_item_no'], unique=False)
    op.alter_column('return_sales', 'customer_name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('return_sales', 'customer_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.drop_index(op.f('ix_product_images_short_item_no'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_is_main'), table_name='product_images')
    op.alter_column('product_images', 'alt_text',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('banners', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('addresses', 'city',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=False)
    op.alter_column('addresses', 'governorate',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=False)
    op.alter_column('Supplier', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('Supplier', 'contact_person',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('Supplier', 'supplier_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=False)
    op.drop_index(op.f('ix_ShortItemNo_en_name'), table_name='ShortItemNo')
    op.drop_index(op.f('ix_ShortItemNo_ar_name'), table_name='ShortItemNo')
    op.alter_column('ShortItemNo', 'sub_header',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'header',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'Brand_Name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'en_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('ShortItemNo', 'ar_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.drop_column('ShortItemNo', 'usage_instructions')
    op.drop_column('ShortItemNo', 'dosage')
    op.alter_column('Sales', 'customer_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('Purchase', 'supplier_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('Orders', 'shipping_city',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('Orders', 'shipping_governorate',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.drop_index(op.f('ix_Category_parent_id'), table_name='Category')
    op.drop_index(op.f('ix_Category_name'), table_name='Category')
    op.alter_column('Category', 'slug',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=True)
    op.alter_column('Category', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Albanian_100_CI_AS_SC_UTF8'),
               existing_nullable=False)
    # ### end Alembic commands ###
