"""add_orders_and_users_to_base

Revision ID: 9f552979e1cb
Revises: e703fd353adf
Create Date: 2026-03-08 23:34:20.034517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f552979e1cb'
down_revision: Union[str, Sequence[str], None] = 'e703fd353adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shipping_first_name', sa.String(length=50), nullable=True),
    sa.Column('shipping_last_name', sa.String(length=50), nullable=True),
    sa.Column('shipping_governorate', sa.String(length=100), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_details', sa.Text(), nullable=True),
    sa.Column('shipping_phone', sa.String(length=20), nullable=True),
    sa.Column('total_raw_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('shipping_fees', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('coupon_discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('points_discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('used_points', sa.Integer(), nullable=True),
    sa.Column('total_final_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Orders_order_number'), 'Orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_Orders_status'), 'Orders', ['status'], unique=False)
    op.create_table('OrderItems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderItems')
    op.drop_index(op.f('ix_Orders_status'), table_name='Orders')
    op.drop_index(op.f('ix_Orders_order_number'), table_name='Orders')
    op.drop_table('Orders')
    # ### end Alembic commands ###
