"""add shipping and locations tables

Revision ID: ac359884a2d7
Revises: 526676f92228
Create Date: 2026-03-14 00:18:51.725458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac359884a2d7'
down_revision: Union[str, Sequence[str], None] = '526676f92228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'name',
               existing_type=sa.VARCHAR(length=50, collation='Albanian_100_CI_AI_WS_SC_UTF8'),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50, collation='Albanian_100_CI_AI_WS_SC_UTF8'),
               existing_nullable=False)
    # ### end Alembic commands ###
