"""update short_item_no relationships

Revision ID: bdd4c7f9d5af
Revises: ac359884a2d7
Create Date: 2026-03-15 22:51:58.568064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd4c7f9d5af'
down_revision: Union[str, Sequence[str], None] = 'ac359884a2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('short_item_no', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ix_Product_short_item_id'), table_name='Product')
    op.create_index(op.f('ix_Product_short_item_no'), 'Product', ['short_item_no'], unique=False)
    op.drop_constraint(op.f('FK__Product__short_i__7EF6D905'), 'Product', type_='foreignkey')
    op.create_foreign_key(None, 'Product', 'ShortItemNo', ['short_item_no'], ['short_item_no'])
    op.drop_column('Product', 'short_item_id')
    op.add_column('product_images', sa.Column('short_item_no', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('FK__product_i__short__1D7B6025'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'ShortItemNo', ['short_item_no'], ['short_item_no'])
    op.drop_column('product_images', 'short_item_id')
    op.add_column('return_sales', sa.Column('short_item_no', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('FK__return_sa__short__1209AD79'), 'return_sales', type_='foreignkey')
    op.create_foreign_key(None, 'return_sales', 'ShortItemNo', ['short_item_no'], ['short_item_no'])
    op.drop_column('return_sales', 'short_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_sales', sa.Column('short_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'return_sales', type_='foreignkey')
    op.create_foreign_key(op.f('FK__return_sa__short__1209AD79'), 'return_sales', 'ShortItemNo', ['short_item_id'], ['id'])
    op.drop_column('return_sales', 'short_item_no')
    op.add_column('product_images', sa.Column('short_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key(op.f('FK__product_i__short__1D7B6025'), 'product_images', 'ShortItemNo', ['short_item_id'], ['id'])
    op.drop_column('product_images', 'short_item_no')
    op.add_column('Product', sa.Column('short_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Product', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Product__short_i__7EF6D905'), 'Product', 'ShortItemNo', ['short_item_id'], ['id'])
    op.drop_index(op.f('ix_Product_short_item_no'), table_name='Product')
    op.create_index(op.f('ix_Product_short_item_id'), 'Product', ['short_item_id'], unique=False)
    op.drop_column('Product', 'short_item_no')
    # ### end Alembic commands ###
