"""initial_full_rebuild

Revision ID: c4cbece81283
Revises: 
Create Date: 2026-04-11 21:39:16.292389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cbece81283'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Category_level'), 'Category', ['level'], unique=False)
    op.create_index(op.f('ix_Category_slug'), 'Category', ['slug'], unique=True)
    op.create_table('ShortItemNo',
    sa.Column('short_item_no', sa.String(length=40), nullable=False),
    sa.Column('ar_name', sa.String(length=100), nullable=True),
    sa.Column('en_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('Brand_Name', sa.String(length=100), nullable=True),
    sa.Column('header', sa.String(length=100), nullable=True),
    sa.Column('sub_header', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('short_item_no')
    )
    op.create_index(op.f('ix_ShortItemNo_Brand_Name'), 'ShortItemNo', ['Brand_Name'], unique=False)
    op.create_index(op.f('ix_ShortItemNo_short_item_no'), 'ShortItemNo', ['short_item_no'], unique=False)
    op.create_table('Supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_table('Classification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_item_no', sa.String(length=40), nullable=False),
    sa.Column('classification_type', sa.String(length=40), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['short_item_no'], ['ShortItemNo.short_item_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('short_item_no', sa.String(length=40), nullable=False),
    sa.Column('stock_quantity', sa.Numeric(precision=18, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=18, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=18, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_new_arrival', sa.Boolean(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['short_item_no'], ['ShortItemNo.short_item_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Product_final_price'), 'Product', ['final_price'], unique=False)
    op.create_index(op.f('ix_Product_is_active'), 'Product', ['is_active'], unique=False)
    op.create_index(op.f('ix_Product_short_item_no'), 'Product', ['short_item_no'], unique=False)
    op.create_index(op.f('ix_Product_slug'), 'Product', ['slug'], unique=True)
    op.create_index(op.f('ix_Product_stock_quantity'), 'Product', ['stock_quantity'], unique=False)
    op.create_table('Purchase',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_no', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('short_item_no', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_code', sa.String(length=20), nullable=True),
    sa.Column('supplier_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('um', sa.String(length=10), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extended_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extended_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('invoice_num', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['short_item_no'], ['ShortItemNo.short_item_no'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['Supplier.id'], ),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('purchase_order_no')
    )
    op.create_table('product_category_link',
    sa.Column('short_item_no', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
    sa.ForeignKeyConstraint(['short_item_no'], ['ShortItemNo.short_item_no'], ),
    sa.PrimaryKeyConstraint('short_item_no', 'category_id')
    )
    op.create_table('Sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('um', sa.String(length=10), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extended_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('customer_code', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_governates', sa.String(length=50), nullable=True),
    sa.Column('customer_city', sa.String(length=50), nullable=True),
    sa.Column('customer_location', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('shipping_fees', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.Column('short_item_no', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('um', sa.String(length=10), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extended_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('customer_code', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_governates', sa.String(length=50), nullable=True),
    sa.Column('customer_city', sa.String(length=50), nullable=True),
    sa.Column('customer_location', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('shipping_fees', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reason_for_return', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['Sales.id'], ),
    sa.ForeignKeyConstraint(['short_item_no'], ['ShortItemNo.short_item_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('short_item_no', sa.String(length=40), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.Column('pickup_governorate', sa.String(length=50), nullable=True),
    sa.Column('pickup_city', sa.String(length=50), nullable=True),
    sa.Column('drop_governorate', sa.String(length=50), nullable=True),
    sa.Column('drop_city', sa.String(length=50), nullable=True),
    sa.Column('shipping_fees', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('transaction_type', sa.Enum('Sales', 'Purchase', name='trans_type'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['Purchase.purchase_id'], ),
    sa.ForeignKeyConstraint(['sales_id'], ['Sales.id'], ),
    sa.ForeignKeyConstraint(['short_item_no'], ['ShortItemNo.short_item_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'OrderItems', 'Product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'OrderItems', 'Orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'Orders', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'Orders', 'coupons', ['coupon_id'], ['id'])
    op.create_foreign_key(None, 'addresses', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'banners', 'Category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'cities', 'governorates', ['governorate_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'points_transactions', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'product_images', 'ShortItemNo', ['short_item_no'], ['short_item_no'])
    op.create_foreign_key(None, 'product_tags_link', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'product_tags_link', 'Product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'social_accounts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'warehouse', 'Product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_constraint(None, 'social_accounts', type_='foreignkey')
    op.drop_constraint(None, 'product_tags_link', type_='foreignkey')
    op.drop_constraint(None, 'product_tags_link', type_='foreignkey')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_constraint(None, 'points_transactions', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_constraint(None, 'banners', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.drop_constraint(None, 'OrderItems', type_='foreignkey')
    op.drop_constraint(None, 'OrderItems', type_='foreignkey')
    op.drop_table('trip')
    op.drop_table('return_sales')
    op.drop_table('Sales')
    op.drop_table('product_category_link')
    op.drop_table('Purchase')
    op.drop_index(op.f('ix_Product_stock_quantity'), table_name='Product')
    op.drop_index(op.f('ix_Product_slug'), table_name='Product')
    op.drop_index(op.f('ix_Product_short_item_no'), table_name='Product')
    op.drop_index(op.f('ix_Product_is_active'), table_name='Product')
    op.drop_index(op.f('ix_Product_final_price'), table_name='Product')
    op.drop_table('Product')
    op.drop_table('Classification')
    op.drop_table('Supplier')
    op.drop_index(op.f('ix_ShortItemNo_short_item_no'), table_name='ShortItemNo')
    op.drop_index(op.f('ix_ShortItemNo_Brand_Name'), table_name='ShortItemNo')
    op.drop_table('ShortItemNo')
    op.drop_index(op.f('ix_Category_slug'), table_name='Category')
    op.drop_index(op.f('ix_Category_level'), table_name='Category')
    op.drop_table('Category')
    # ### end Alembic commands ###
