"""change_pk_to_short_item_no

Revision ID: d4528bc371c8
Revises: 
Create Date: 2026-04-11 16:26:34.875599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4528bc371c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Product', 'short_item_no',
               existing_type=sa.VARCHAR(length=20, collation='Albanian_100_CI_AI_WS_SC_UTF8'),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('ShortItemNo', 'short_item_no',
               existing_type=sa.VARCHAR(length=20, collation='Albanian_100_CI_AI_WS_SC_UTF8'),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.drop_index(op.f('ix_ShortItemNo_short_item_no'), table_name='ShortItemNo')
    op.create_index(op.f('ix_ShortItemNo_short_item_no'), 'ShortItemNo', ['short_item_no'], unique=False)
    op.alter_column('product_images', 'short_item_no',
               existing_type=sa.VARCHAR(length=20, collation='Albanian_100_CI_AI_WS_SC_UTF8'),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'short_item_no',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20, collation='Albanian_100_CI_AI_WS_SC_UTF8'),
               existing_nullable=False)
    op.drop_index(op.f('ix_ShortItemNo_short_item_no'), table_name='ShortItemNo')
    op.create_index(op.f('ix_ShortItemNo_short_item_no'), 'ShortItemNo', ['short_item_no'], unique=True)
    op.alter_column('ShortItemNo', 'short_item_no',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20, collation='Albanian_100_CI_AI_WS_SC_UTF8'),
               existing_nullable=False)
    op.alter_column('Product', 'short_item_no',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20, collation='Albanian_100_CI_AI_WS_SC_UTF8'),
               existing_nullable=False)
    # ### end Alembic commands ###
